language: node_js

node_js:
  - '8'

cache: yarn

branches:
  only:
   - master

before_script:
 - yarn install --production
 - yarn -D add typescript@~2.5.3 @angular/compiler-cli@^5.2.0

script:
 - npm run build

notifications:
 email:
     recipients:
       - azrizhaziq@gmail.com
     on_success: never # default: change
     on_failure: always # default: always
