language: node_js
node_js:
  - '7'

branches:
  only:
   - master

before_script:
 - yarn install

script:
 - npm run build

notifications:
 email:
     recipients:
       - azrizhaziq@gmail.com
     on_success: never # default: change
     on_failure: always # default: always
